
USE `SPRINGDEMO`;

CREATE TABLE IF NOT EXISTS `ADMIN_USERS` (
   `ID` BIGINT NOT NULL AUTO_INCREMENT,
   FULL_NAME VARCHAR(200) NOT NULL,
   EMAIL VARCHAR(200) NOT NULL,
   MOBILE VARCHAR(20) NOT NULL,
   USERNAME VARCHAR(200) NOT NULL,
   PASSWORD VARCHAR(200) NOT NULL,
   ROLE VARCHAR(1) NOT NULL,
   CREATED_BY VARCHAR(200) NOT NULL,
   CREATED_DATE DATETIME NOT NULL,
   UPDATED_BY VARCHAR(200) NOT NULL,
   UPDATED_DATE DATETIME NOT NULL,
   DELETED VARCHAR(1) NOT NULL,
   PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

CREATE INDEX `UNIQ_USR_I` ON `ADMIN_USERS` (USERNAME, DELETED);
